# Financiamiento Privado en Mercado de Capitales. Dólares.
Financiamiento Privado en Mercado de Capitales por tamaño de empresa e instrumento, monto en dólares.

In [1]:
# Comenzamos importando las librerias a utilizar por el momento.

import numpy as np   # Importamos librerias de calculo
import pandas as pd  # Importamos librerias de uso de tablas o los dataframes
import seaborn as sns # Importamos librerias de graficos
%matplotlib inline
import matplotlib.pyplot as plt

Direccion del dataset

https://datos.gob.ar/dataset/sspm-financiamiento-privado-mercado-capitales/archivo/sspm_170.1

In [2]:
# Ubicar el dataset, cargarlo y mostrarlo.
url='https://raw.githubusercontent.com/NestorDiazDataSC/Analisis_de_Datos/main/Financiamiento_Privado_Mercado_Capitales/financiamiento-privado-mercado-capitales-dolares.csv'

df= pd.read_csv(url)
df

,indice_tiempo,financiamiento_mercado_capitales_ge_on_vcp,financiamiento_mercado_capitales_ge_ff,financiamiento_mercado_capitales_ge_acciones,financiamiento_mercado_capitales_ge_cdcp,financiamiento_mercado_capitales_ge_total,financiamiento_mercado_capitales_pymes_on_vcp,financiamiento_mercado_capitales_pymes_ff,financiamiento_mercado_capitales_pymes_acciones,financiamiento_mercado_capitales_pymes_cdcp,...,manufacturas_origen_agropecuario,manufacturas_origen_industrial,manufacturas_actividades_empresariales,manufacturas_papel_celulosa,manufacturas_servicios_informaticos,manufacturas_tecnologia,manufacturas_telecomunicaciones,manufacturas_transporte_energia_electrica,manufacturas_transporte_gas,manufacturas_transporte_pasajeros_peajes
0,2007-01-01,3.000000e+08,2.642723e+08,1.017422e+07,1.809615e+06,5.762561e+08,2.500000e+05,3.042050e+06,NaN,1.454448e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,2007-02-01,NaN,1.053984e+08,4.302251e+08,1.221314e+06,5.368448e+08,NaN,7.508643e+06,NaN,1.233830e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-03-01,NaN,1.704575e+08,NaN,2.353346e+06,1.728108e+08,3.215434e+05,2.615312e+07,NaN,1.546019e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-04-01,1.718089e+08,1.197570e+08,7.045493e+07,3.086170e+06,3.651070e+08,NaN,1.486692e+06,NaN,1.224757e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-05-01,1.325000e+09,1.687936e+08,NaN,2.176995e+06,1.495971e+09,NaN,7.814367e+06,NaN,1.292232e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2022-03-01,9.232671e+07,6.933919e+07,NaN,NaN,1.616659e+08,4.134795e+06,3.394862e+06,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.459381,NaN,NaN,NaN
183,2022-04-01,1.029188e+08,7.868771e+07,NaN,NaN,1.816066e+08,1.854224e+07,1.371023e+07,NaN,NaN,...,0.036494,0.026766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,2022-05-01,4.408777e+08,5.636723e+07,NaN,NaN,4.972449e+08,6.854434e+06,4.163517e+06,NaN,NaN,...,0.014184,NaN,0.001125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,2022-06-01,4.000784e+08,1.073972e+08,NaN,NaN,5.074756e+08,3.792692e+07,4.987449e+06,NaN,NaN,...,0.014540,0.040982,NaN,NaN,NaN,NaN,0.009022,NaN,NaN,NaN
186,2022-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns # Para ver las columnas del Dataset, para esta parte del analisis voy a usar las primeras 13 columnas que tienen datos sobre el financiamiento.

Index(['indice_tiempo', 'financiamiento_mercado_capitales_ge_on_vcp',
       'financiamiento_mercado_capitales_ge_ff',
       'financiamiento_mercado_capitales_ge_acciones',
       'financiamiento_mercado_capitales_ge_cdcp',
       'financiamiento_mercado_capitales_ge_total',
       'financiamiento_mercado_capitales_pymes_on_vcp',
       'financiamiento_mercado_capitales_pymes_ff',
       'financiamiento_mercado_capitales_pymes_acciones',
       'financiamiento_mercado_capitales_pymes_cdcp',
       'financiamiento_mercado_capitales_pymes_pagares',
       'financiamiento_mercado_capitales_pymes_total',
       'financiamiento_mercado_capitales_total_general',
       'tasa_interes_vdf_senior', 'tasa_interes_cpdp', 'tasa_interes_cpda',
       'emisiones_ge_on', 'emisiones_ge_ff', 'emisiones_ge_acc',
       'emisiones_ge_cpd', 'emisiones_ge_total', 'emisiones_pymes_on',
       'emisiones_pymes_ff', 'emisiones_pymes_acc', 'emisiones_pymes_cpd',
       'emisiones_pymes_pag', 'emisiones_pymes_total',
       'emisiones_totales_ge_pymes', 'eff_agropecuarios', 'eff_estructurados',
       'eff_creditos_comerciales', 'eff_flujos_futuros',
       'eff_inmobiliario_hipotecario', 'eff_leasing', 'eff_prendarios',
       'eff_obras_publicas', 'eff_prestamos_personales_consumo',
       'eff_tarjetas_credito', 'eff_innovacion_financiera',
       'eff_financiacion_exportaciones', 'act_financieras_seguros',
       'actividades_inmobiliarias', 'agricultura_ganaderia',
       'alimentos_bebidas', 'bancos', 'calzado_indumentaria', 'comercio',
       'construccion', 'distribucion_energia_electrica', 'distribucion_de_gas',
       'editoriales_imprentas', 'equipamiento_hogar',
       'generacion_energia_electrica', 'grupos_concesionarios', 'holdings',
       'industria_automotriz', 'industria_petroleo_gas',
       'industria_farmaceutica', 'industria_metalurgica_siderurgica',
       'industria_quimica_petroquimica', 'manufacturas_origen_agropecuario',
       'manufacturas_origen_industrial',
       'manufacturas_actividades_empresariales', 'manufacturas_papel_celulosa',
       'manufacturas_servicios_informaticos', 'manufacturas_tecnologia',
       'manufacturas_telecomunicaciones',
       'manufacturas_transporte_energia_electrica',
       'manufacturas_transporte_gas',
       'manufacturas_transporte_pasajeros_peajes'],
      dtype='object')

In [4]:
# Elimino las columnas que no voy a utilizar del dataset
df = df.drop(df.columns[13:77], axis=1)

In [5]:
df.columns # Verifico que quedaron solo las columnas que necesito

Index(['indice_tiempo', 'financiamiento_mercado_capitales_ge_on_vcp',
       'financiamiento_mercado_capitales_ge_ff',
       'financiamiento_mercado_capitales_ge_acciones',
       'financiamiento_mercado_capitales_ge_cdcp',
       'financiamiento_mercado_capitales_ge_total',
       'financiamiento_mercado_capitales_pymes_on_vcp',
       'financiamiento_mercado_capitales_pymes_ff',
       'financiamiento_mercado_capitales_pymes_acciones',
       'financiamiento_mercado_capitales_pymes_cdcp',
       'financiamiento_mercado_capitales_pymes_pagares',
       'financiamiento_mercado_capitales_pymes_total',
       'financiamiento_mercado_capitales_total_general'],
      dtype='object')

In [6]:
df.columns = ['Fecha', 'ON GE', 'FF GE', 'ACC GE', 'CHPD GE', 'TOTAL GE', 'ON PyMES', 'FF PyMES', 'ACC PyMES', 'CHPD PyMES','PAG PyMES','TOTAL PyMES', 'TOTAL']

Descripcion de las columnas del dataset, los valores numericos estan expresados en dolares.

*   ON = Obligaciones negociables emitidas, monto
*   FF = Fideicomisos Financieros, emitidos
*   ACC = Acciones emitidas
*   CHPD = Cheques de pago diferidos emitidos
*   PAG = Pagares emitidos
*   GE = Grandes Empresas
*   PyMES = Pequeñas y medianas empresas

In [7]:
df.sample(5)

,Fecha,ON GE,FF GE,ACC GE,CHPD GE,TOTAL GE,ON PyMES,FF PyMES,ACC PyMES,CHPD PyMES,PAG PyMES,TOTAL PyMES,TOTAL
88,2014-05-01,1.751894e+08,1.580851e+08,2.638371e+07,9.971936e+05,3.606554e+08,NaN,NaN,NaN,4.289966e+07,NaN,4.289966e+07,4.035550e+08
116,2016-09-01,7.917067e+08,1.635563e+08,NaN,1.424464e+06,9.566875e+08,2.608412e+06,NaN,NaN,1.023567e+08,3956765.71,1.089219e+08,1.065609e+09
66,2012-07-01,8.992038e+07,2.189890e+08,NaN,1.426049e+06,3.103354e+08,1.876380e+06,7.671873e+06,NaN,4.417048e+07,NaN,5.371874e+07,3.640542e+08
82,2013-11-01,5.390609e+08,3.164072e+08,9.079755e+07,1.069074e+06,9.473347e+08,NaN,NaN,NaN,4.619345e+07,NaN,4.619345e+07,9.935282e+08
146,2019-03-01,3.374542e+07,9.425944e+07,NaN,NaN,1.280049e+08,NaN,9.482004e+06,NaN,NaN,NaN,9.482004e+06,1.374869e+08

In [8]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        187 non-null    object
 1   ON GE        179 non-null    float64
 2   FF GE        186 non-null    float64
 3   ACC GE       50 non-null     float64
 4   CHPD GE      139 non-null    float64
 5   TOTAL GE     186 non-null    float64
 6   ON PyMES     113 non-null    float64
 7   FF PyMES     117 non-null    float64
 8   ACC PyMES    2 non-null      float64
 9   CHPD PyMES   140 non-null    float64
 10  PAG PyMES    35 non-null     float64
 11  TOTAL PyMES  184 non-null    float64
 12  TOTAL        186 non-null    float64
dtypes: float64(12), object(1)
memory usage: 19.1+ KB

(187, 13)

In [9]:
df.isnull().sum() # Para ver los valores nulos de cada columna.

Fecha            0
ON GE            8
FF GE            1
ACC GE         137
CHPD GE         48
TOTAL GE         1
ON PyMES        74
FF PyMES        70
ACC PyMES      185
CHPD PyMES      47
PAG PyMES      152
TOTAL PyMES      3
TOTAL            1
dtype: int64

In [21]:
# En estos casos de abajo, reemplazo los valores nulos por "0" puesto que son nulos porque no hubo emisión en esos casos.
df["ON GE"].fillna(0, inplace = True)
df["FF GE"].fillna(0, inplace = True)
df["ACC GE"].fillna(0, inplace = True)
df["CHPD GE"].fillna(0, inplace = True)
df["ON PyMES"].fillna(0, inplace = True)
df["FF PyMES"].fillna(0, inplace = True)
df["ACC PyMES"].fillna(0, inplace = True)
df["CHPD PyMES"].fillna(0, inplace = True)
df["PAG PyMES"].fillna(0, inplace = True)
# En estos casos no puedo poner "0" porque son totales, sumas de varios valores, por lo que relleno con esas sumas.
df["TOTAL GE"].fillna(df["ON GE"] + df["FF GE"] + df["ACC GE"] + df["CHPD GE"], inplace = True)
df["TOTAL PyMES"].fillna(df["ON PyMES"] + df["FF PyMES"] + df["ACC PyMES"] + df["CHPD PyMES"] + df["PAG PyMES"], inplace = True)
df["TOTAL"].fillna(df["TOTAL GE"] + df["TOTAL PyMES"], inplace = True)

In [22]:
df.isnull().sum() # Para ver los valores nulos de cada columna.

Fecha          0
ON GE          0
FF GE          0
ACC GE         0
CHPD GE        0
TOTAL GE       0
ON PyMES       0
FF PyMES       0
ACC PyMES      0
CHPD PyMES     0
PAG PyMES      0
TOTAL PyMES    0
TOTAL          0
dtype: int64