# Financiamiento Privado en Mercado de Capitales. Dólares.
Financiamiento Privado en Mercado de Capitales por tamaño de empresa e instrumento, monto en dólares.

In [1]:
# Comenzamos importando las librerias a utilizar por el momento.

import numpy as np   # Importamos librerias de calculo
import pandas as pd  # Importamos librerias de uso de tablas o los dataframes
import seaborn as sns # Importamos librerias de graficos
%matplotlib inline
import matplotlib.pyplot as plt

Direccion del dataset

https://datos.gob.ar/dataset/sspm-financiamiento-privado-mercado-capitales/archivo/sspm_170.1

In [2]:
# Ubicar el dataset, cargarlo y mostrarlo.
url='https://raw.githubusercontent.com/NestorDiazDataSC/Analisis_de_Datos/main/Financiamiento_Privado_Mercado_Capitales/financiamiento-privado-mercado-capitales-dolares.csv'

df= pd.read_csv(url)
df

,indice_tiempo,financiamiento_mercado_capitales_ge_on_vcp,financiamiento_mercado_capitales_ge_ff,financiamiento_mercado_capitales_ge_acciones,financiamiento_mercado_capitales_ge_cdcp,financiamiento_mercado_capitales_ge_total,financiamiento_mercado_capitales_pymes_on_vcp,financiamiento_mercado_capitales_pymes_ff,financiamiento_mercado_capitales_pymes_acciones,financiamiento_mercado_capitales_pymes_cdcp,...,manufacturas_origen_agropecuario,manufacturas_origen_industrial,manufacturas_actividades_empresariales,manufacturas_papel_celulosa,manufacturas_servicios_informaticos,manufacturas_tecnologia,manufacturas_telecomunicaciones,manufacturas_transporte_energia_electrica,manufacturas_transporte_gas,manufacturas_transporte_pasajeros_peajes
0,2007-01-01,3.000000e+08,2.642723e+08,1.017422e+07,1.809615e+06,5.762561e+08,2.500000e+05,3.042050e+06,NaN,1.454448e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,2007-02-01,NaN,1.053984e+08,4.302251e+08,1.221314e+06,5.368448e+08,NaN,7.508643e+06,NaN,1.233830e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-03-01,NaN,1.704575e+08,NaN,2.353346e+06,1.728108e+08,3.215434e+05,2.615312e+07,NaN,1.546019e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-04-01,1.718089e+08,1.197570e+08,7.045493e+07,3.086170e+06,3.651070e+08,NaN,1.486692e+06,NaN,1.224757e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-05-01,1.325000e+09,1.687936e+08,NaN,2.176995e+06,1.495971e+09,NaN,7.814367e+06,NaN,1.292232e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,2022-03-01,9.232671e+07,6.933919e+07,NaN,NaN,1.616659e+08,4.134795e+06,3.394862e+06,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.459381,NaN,NaN,NaN
183,2022-04-01,1.029188e+08,7.868771e+07,NaN,NaN,1.816066e+08,1.854224e+07,1.371023e+07,NaN,NaN,...,0.036494,0.026766,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,2022-05-01,4.408777e+08,5.636723e+07,NaN,NaN,4.972449e+08,6.854434e+06,4.163517e+06,NaN,NaN,...,0.014184,NaN,0.001125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,2022-06-01,4.000784e+08,1.073972e+08,NaN,NaN,5.074756e+08,3.792692e+07,4.987449e+06,NaN,NaN,...,0.014540,0.040982,NaN,NaN,NaN,NaN,0.009022,NaN,NaN,NaN
186,2022-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.columns # Para ver las columnas del Dataset, para esta parte del analisis voy a usar las primeras 13 columnas que tienen datos sobre el financiamiento.

Index(['indice_tiempo', 'financiamiento_mercado_capitales_ge_on_vcp',
       'financiamiento_mercado_capitales_ge_ff',
       'financiamiento_mercado_capitales_ge_acciones',
       'financiamiento_mercado_capitales_ge_cdcp',
       'financiamiento_mercado_capitales_ge_total',
       'financiamiento_mercado_capitales_pymes_on_vcp',
       'financiamiento_mercado_capitales_pymes_ff',
       'financiamiento_mercado_capitales_pymes_acciones',
       'financiamiento_mercado_capitales_pymes_cdcp',
       'financiamiento_mercado_capitales_pymes_pagares',
       'financiamiento_mercado_capitales_pymes_total',
       'financiamiento_mercado_capitales_total_general',
       'tasa_interes_vdf_senior', 'tasa_interes_cpdp', 'tasa_interes_cpda',
       'emisiones_ge_on', 'emisiones_ge_ff', 'emisiones_ge_acc',
       'emisiones_ge_cpd', 'emisiones_ge_total', 'emisiones_pymes_on',
       'emisiones_pymes_ff', 'emisiones_pymes_acc', 'emisiones_pymes_cpd',
       'emisiones_pymes_pag', 'emisiones_pymes_total',
       'emisiones_totales_ge_pymes', 'eff_agropecuarios', 'eff_estructurados',
       'eff_creditos_comerciales', 'eff_flujos_futuros',
       'eff_inmobiliario_hipotecario', 'eff_leasing', 'eff_prendarios',
       'eff_obras_publicas', 'eff_prestamos_personales_consumo',
       'eff_tarjetas_credito', 'eff_innovacion_financiera',
       'eff_financiacion_exportaciones', 'act_financieras_seguros',
       'actividades_inmobiliarias', 'agricultura_ganaderia',
       'alimentos_bebidas', 'bancos', 'calzado_indumentaria', 'comercio',
       'construccion', 'distribucion_energia_electrica', 'distribucion_de_gas',
       'editoriales_imprentas', 'equipamiento_hogar',
       'generacion_energia_electrica', 'grupos_concesionarios', 'holdings',
       'industria_automotriz', 'industria_petroleo_gas',
       'industria_farmaceutica', 'industria_metalurgica_siderurgica',
       'industria_quimica_petroquimica', 'manufacturas_origen_agropecuario',
       'manufacturas_origen_industrial',
       'manufacturas_actividades_empresariales', 'manufacturas_papel_celulosa',
       'manufacturas_servicios_informaticos', 'manufacturas_tecnologia',
       'manufacturas_telecomunicaciones',
       'manufacturas_transporte_energia_electrica',
       'manufacturas_transporte_gas',
       'manufacturas_transporte_pasajeros_peajes'],
      dtype='object')

In [4]:
# Elimino las columnas que no voy a utilizar del dataset
df = df.drop(df.columns[13:77], axis=1)

In [5]:
df.columns # Verifico que quedaron solo las columnas que necesito

Index(['indice_tiempo', 'financiamiento_mercado_capitales_ge_on_vcp',
       'financiamiento_mercado_capitales_ge_ff',
       'financiamiento_mercado_capitales_ge_acciones',
       'financiamiento_mercado_capitales_ge_cdcp',
       'financiamiento_mercado_capitales_ge_total',
       'financiamiento_mercado_capitales_pymes_on_vcp',
       'financiamiento_mercado_capitales_pymes_ff',
       'financiamiento_mercado_capitales_pymes_acciones',
       'financiamiento_mercado_capitales_pymes_cdcp',
       'financiamiento_mercado_capitales_pymes_pagares',
       'financiamiento_mercado_capitales_pymes_total',
       'financiamiento_mercado_capitales_total_general'],
      dtype='object')

In [6]:
df.columns = ['Fecha', 'ON GE', 'FF GE', 'ACC GE', 'CHPD GE', 'TOTAL GE', 'ON PyMES', 'FF PyMES', 'ACC PyMES', 'CHPD PyMES','PAG PyMES','TOTAL PyMES', 'TOTAL']

Descripcion de las columnas del dataset, los valores numericos estan expresados en dolares.

*   ON = Obligaciones negociables emitidas, monto
*   FF = Fideicomisos Financieros, emitidos
*   ACC = Acciones emitidas
*   CHPD = Cheques de pago diferidos emitidos
*   PAG = Pagares emitidos
*   GE = Grandes Empresas
*   PyMES = Pequeñas y medianas empresas

In [7]:
df.sample(5)

,Fecha,ON GE,FF GE,ACC GE,CHPD GE,TOTAL GE,ON PyMES,FF PyMES,ACC PyMES,CHPD PyMES,PAG PyMES,TOTAL PyMES,TOTAL
46,2010-11-01,4.522776e+08,5.975347e+08,NaN,6.183475e+05,1.050431e+09,3.500000e+06,9.931331e+06,NaN,2.531357e+07,NaN,3.874490e+07,1.089175e+09
94,2014-11-01,2.636016e+08,1.344943e+08,NaN,1.087670e+06,3.991836e+08,3.863812e+06,1.173021e+07,NaN,4.958732e+07,NaN,6.518133e+07,4.643650e+08
61,2012-02-01,1.157844e+08,2.357136e+08,NaN,1.279426e+06,3.527775e+08,NaN,NaN,NaN,2.244726e+07,NaN,2.244726e+07,3.752247e+08
33,2009-10-01,4.295729e+07,1.554075e+08,37058347.74,9.619256e+05,2.363851e+08,NaN,7.544400e+06,NaN,1.810366e+07,NaN,2.564806e+07,2.620331e+08
117,2016-10-01,7.382586e+08,1.799775e+08,NaN,1.526151e+06,9.197622e+08,NaN,5.115000e+06,NaN,5.265756e+07,1111478.52,5.888404e+07,9.786462e+08

In [8]:
df.info()
print()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Fecha        187 non-null    object
 1   ON GE        179 non-null    float64
 2   FF GE        186 non-null    float64
 3   ACC GE       50 non-null     float64
 4   CHPD GE      139 non-null    float64
 5   TOTAL GE     186 non-null    float64
 6   ON PyMES     113 non-null    float64
 7   FF PyMES     117 non-null    float64
 8   ACC PyMES    2 non-null      float64
 9   CHPD PyMES   140 non-null    float64
 10  PAG PyMES    35 non-null     float64
 11  TOTAL PyMES  184 non-null    float64
 12  TOTAL        186 non-null    float64
dtypes: float64(12), object(1)
memory usage: 19.1+ KB

(187, 13)

In [9]:
df.isnull().sum() # Para ver los valores nulos de cada columna.

Fecha            0
ON GE            8
FF GE            1
ACC GE         137
CHPD GE         48
TOTAL GE         1
ON PyMES        74
FF PyMES        70
ACC PyMES      185
CHPD PyMES      47
PAG PyMES      152
TOTAL PyMES      3
TOTAL            1
dtype: int64

In [10]:
# En estos casos de abajo, reemplazo los valores nulos por "0" puesto que son nulos porque no hubo emisión en esos casos.
df["ON GE"].fillna(0, inplace = True)
df["FF GE"].fillna(0, inplace = True)
df["ACC GE"].fillna(0, inplace = True)
df["CHPD GE"].fillna(0, inplace = True)
df["ON PyMES"].fillna(0, inplace = True)
df["FF PyMES"].fillna(0, inplace = True)
df["ACC PyMES"].fillna(0, inplace = True)
df["CHPD PyMES"].fillna(0, inplace = True)
df["PAG PyMES"].fillna(0, inplace = True)
# En estos casos no puedo poner "0" porque son totales, sumas de varios valores, por lo que relleno con esas sumas.
df["TOTAL GE"].fillna(df["ON GE"] + df["FF GE"] + df["ACC GE"] + df["CHPD GE"], inplace = True)
df["TOTAL PyMES"].fillna(df["ON PyMES"] + df["FF PyMES"] + df["ACC PyMES"] + df["CHPD PyMES"] + df["PAG PyMES"], inplace = True)
df["TOTAL"].fillna(df["TOTAL GE"] + df["TOTAL PyMES"], inplace = True)

In [11]:
df.isnull().sum() # Para ver los valores nulos de cada columna.

Fecha          0
ON GE          0
FF GE          0
ACC GE         0
CHPD GE        0
TOTAL GE       0
ON PyMES       0
FF PyMES       0
ACC PyMES      0
CHPD PyMES     0
PAG PyMES      0
TOTAL PyMES    0
TOTAL          0
dtype: int64

In [12]:
# Ahora vemos que nos trae el booleano FALSE porque ya no hay mas valores NAN en el dataframe y podemos seguir trabajando.
check_for_nan = df.isnull().values.any()
print (check_for_nan)

False

#NORMALIZACION DE DATOS

In [13]:
# Primer codigo para reducir el valor, para expresarlo en millones.
# Segundo renglon de codigo, para convertir numeros que estan en "notación cientifica" a numeros para que sea mas facil de interpretar y tambien que sean "Float"
df ["ON GE"] = df ["ON GE"] / 1000
df['ON GE'] = df['ON GE'].apply(lambda x: float('{:.0f}'.format(x)))

df ["FF GE"] = df ["FF GE"] / 1000
df['FF GE'] = df['FF GE'].apply(lambda x: float('{:.0f}'.format(x)))

df ["ACC GE"] = df ["ACC GE"] / 1000
df['ACC GE'] = df['ACC GE'].apply(lambda x: float('{:.0f}'.format(x)))

df ["CHPD GE"] = df ["CHPD GE"] / 1000
df['CHPD GE'] = df['CHPD GE'].apply(lambda x: float('{:.0f}'.format(x)))

df ["TOTAL GE"] = df ["TOTAL GE"] / 1000
df['TOTAL GE'] = df['TOTAL GE'].apply(lambda x: float('{:.0f}'.format(x)))

df ["ON PyMES"] = df ["ON PyMES"] / 1000
df['ON PyMES'] = df['ON PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["FF PyMES"] = df ["FF PyMES"] / 1000
df['FF PyMES'] = df['FF PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["ACC PyMES"] = df ["ACC PyMES"] / 1000
df['ACC PyMES'] = df['ACC PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["CHPD PyMES"] = df ["CHPD PyMES"] / 1000
df['CHPD PyMES'] = df['CHPD PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["PAG PyMES"] = df ["PAG PyMES"] / 1000
df['PAG PyMES'] = df['PAG PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["TOTAL PyMES"] = df ["TOTAL PyMES"] / 1000
df['TOTAL PyMES'] = df['TOTAL PyMES'].apply(lambda x: float('{:.0f}'.format(x)))

df ["TOTAL"] = df ["TOTAL"] / 1000
df['TOTAL'] = df['TOTAL'].apply(lambda x: float('{:.0f}'.format(x)))

In [14]:
df.sample(4)

,Fecha,ON GE,FF GE,ACC GE,CHPD GE,TOTAL GE,ON PyMES,FF PyMES,ACC PyMES,CHPD PyMES,PAG PyMES,TOTAL PyMES,TOTAL
14,2008-03-01,0.0,207781.0,291206.0,1469.0,500456.0,350.0,17863.0,0.0,13157.0,0.0,31370.0,531826.0
124,2017-05-01,1506671.0,229419.0,0.0,645.0,1736736.0,0.0,0.0,0.0,79748.0,7138.0,86886.0,1823622.0
128,2017-09-01,242613.0,210700.0,891800.0,324.0,1345437.0,4738.0,0.0,0.0,64811.0,14259.0,83808.0,1429245.0
73,2013-02-01,459260.0,243740.0,0.0,1250.0,704251.0,2185.0,0.0,0.0,27747.0,0.0,29932.0,734183.0

# APLICANDO ESTADISTICA

In [17]:
df.corr()

<ipython-input-17-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,ON GE,FF GE,ACC GE,CHPD GE,TOTAL GE,ON PyMES,FF PyMES,ACC PyMES,CHPD PyMES,PAG PyMES,TOTAL PyMES,TOTAL
ON GE,1.000000,-0.025642,-0.013840,-0.030974,0.840971,0.139336,-0.222979,0.064329,0.297813,0.241843,0.292250,0.837961
FF GE,-0.025642,1.000000,-0.025068,0.280951,0.472818,-0.125681,0.092760,0.095819,0.187228,-0.063349,0.171920,0.471614
ACC GE,-0.013840,-0.025068,1.000000,0.038401,0.194492,0.028868,-0.020511,-0.007716,0.151083,0.307886,0.185679,0.201384
CHPD GE,-0.030974,0.280951,0.038401,1.000000,0.121978,-0.269389,0.196566,0.085065,0.285007,-0.215883,0.244227,0.134511
TOTAL GE,0.840971,0.472818,0.194492,0.121978,1.000000,0.061674,-0.149187,0.101384,0.380679,0.242140,0.375590,0.998225
ON PyMES,0.139336,-0.125681,0.028868,-0.269389,0.061674,1.000000,-0.015471,0.003624,-0.046611,0.110551,0.119315,0.067742
FF PyMES,-0.222979,0.092760,-0.020511,0.196566,-0.149187,-0.015471,1.000000,0.004790,-0.223157,-0.224718,-0.034907,-0.147564
ACC PyMES,0.064329,0.095819,-0.007716,0.085065,0.101384,0.003624,0.004790,1.000000,0.003704,-0.034305,0.019104,0.099985
CHPD PyMES,0.297813,0.187228,0.151083,0.285007,0.380679,-0.046611,-0.223157,0.003704,1.000000,0.451243,0.960835,0.432557
PAG PyMES,0.241843,-0.063349,0.307886,-0.215883,0.242140,0.110551,-0.224718,-0.034305,0.451243,1.000000,0.534748,0.270228
TOTAL PyMES,0.292250,0.171920,0.185679,0.244227,0.375590,0.119315,-0.034907,0.019104,0.960835,0.534748,1.000000,0.430117
TOTAL,0.837961,0.471614,0.201384,0.134511,0.998225,0.067742,-0.147564,0.099985,0.432557,0.270228,0.430117,1.000000